//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_SGC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int ID_Curso { get; set; }
        public string NombreCurso { get; set; }
        public double Precio_Curso { get; set; }
        public int Creditos { get; set; }
        public int IdPlanEstudio { get; set; }
    
        public virtual PlanEstudio PlanEstudio { get; set; }
    }
}
