//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_SGC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int ID_Curso { get; set; }
        public string NombreCurso { get; set; }
        public double Precio_Curso { get; set; }
        public int Creditos { get; set; }
        public int IdPlanEstudio { get; set; }
    
        public virtual PlanEstudio PlanEstudio { get; set; }
    }
}
