//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_SGC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetodoPago
    {
        public int ID_MetodoPago { get; set; }
        public string Nombre_Metodo { get; set; }
    }
}
